import argparse
import logging
from pathlib import Path

import numpy as np
import polars as pl
from scipy.signal import stft
from scipy.stats import kurtosis, skew
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
import gc
from tqdm import tqdm

pl.Config.set_tbl_rows(-1)       # show all rows
pl.Config.set_tbl_cols(-1)       # show all columns
pl.Config.set_fmt_str_lengths(200)  # don't truncate long strings (like your trial names)
pl.Config.set_tbl_width_chars(-1)   # don't wrap based on terminal width

"""
The Class for the Medalian Pipeline

Expects a str with the path to the folder containing the files to process

Expects that the files are .parquet
"""


class Pipeline:
    def __init__(
        self,
        data_path: str,
        bronze_data_path: str,
        silver_data_path: str,
        gold_data_path: str,
    ):
        self.data_path = data_path
        self.bronze_data_path = bronze_data_path
        self.silver_data_path = silver_data_path
        self.gold_data_path = gold_data_path

        # if any of the necessary folders don't exist, create them
        Path(data_path).mkdir(parents=True, exist_ok=True)
        for path in [bronze_data_path, silver_data_path, gold_data_path]:
            Path(path).parent.mkdir(parents=True, exist_ok=True)

    def bronze_check_missing_data(self, path):
        df = pl.read_parquet(path)
        null_count = df.null_count().sum_horizontal().item()
        nan_count = (
            df.select(pl.col(pl.Float32, pl.Float64).is_nan().sum())
            .sum_horizontal()
            .item()
        )
        return null_count + nan_count

    def bronze_check_bad_runs(self, df: pl.DataFrame, signal_cols, min_samples=25):
        cols = [c for c in signal_cols if c in df.columns]

        run_stats = df.group_by("run").agg(
            [pl.len().alias("n")]
            + [pl.col(c).abs().sum().alias(f"{c}_abssum") for c in cols]
            + [pl.col(c).std().alias(f"{c}_std") for c in cols]
        )

        bad_short = run_stats.filter(pl.col("n") < min_samples)["run"]
        bad_zero = set()
        bad_std = set()
        for c in cols:
            bad_zero |= set(run_stats.filter(pl.col(f"{c}_abssum") == 0)["run"])
            bad_std |= set(run_stats.filter(pl.col(f"{c}_std") == 0)["run"])


        return set(bad_short) | set(bad_zero) | set(bad_std)

    def gold_remove_outliers(self, df: pl.DataFrame):
        X = df.select(pl.exclude(['trial', 'run', 'fault_mode', 'routine'])).to_numpy()
        logging.info("SILVER LAYER: Removing Outliers...")
        iso = IsolationForest(contamination=0.03, random_state=42, verbose=0)
        outliers = iso.fit_predict(X)  # -1 = outlier, 1 = inlier
        cleaned_df = df.filter(pl.Series(outliers) == 1)
        logging.info(f"SILVER LAYER: done, df is: {df.height} rows, {len(df.columns)} cols")
        del X, iso, outliers
        gc.collect()
        return cleaned_df

    def compute_spectral_kurtosis(
        self, x: np.ndarray, fs: float, nperseg: int
    ) -> np.ndarray:
        """Returns K(f): one spectral kurtosis value per frequency bin,
        averaged over time per Antoni's definition."""
        _, _, S = stft(x, fs=fs, nperseg=nperseg)
        mag = np.abs(S)  # shape: (freq, time)
        mag2 = mag**2
        mag4 = mag**4
        mean_mag2 = mag2.mean(axis=1)
        mean_mag4 = mag4.mean(axis=1)
        K_f = mean_mag4 / (mean_mag2**2) - 2
        return K_f

    def compute_row_stats(self, df: pl.DataFrame, value_col: str, SAMPLE_RATE) -> dict:
        # TODO: fix any nulls being generated by this function
        NPERSEG = int(len(df) / 25)
        x = df[value_col].to_numpy().astype(np.float64)

        if len(x) < 25 or np.all(x == 0) or np.std(x) == 0:
            logging.warning(
                f"{value_col}: degenerate signal, len={len(x)}, std={np.std(x)}"
            )

        mean_ = x.mean()
        std_ = x.std()
        rms = np.sqrt(np.mean(x**2))
        kurt = kurtosis(x, fisher=True, bias=False)
        skw = skew(x, bias=False)
        p2p = x.max() - x.min()
        abs_x = np.abs(x)
        crest = abs_x.max() / rms
        shape_factor = rms / abs_x.mean()
        impulse_factor = abs_x.max() / abs_x.mean()
        margin_factor = abs_x.max() / (np.mean(np.sqrt(abs_x)) ** 2)
        energy = np.sum(x**2)

        K_f = self.compute_spectral_kurtosis(x, SAMPLE_RATE, NPERSEG)
        sk_mean = K_f.mean()
        sk_std = K_f.std()
        sk_skew = skew(K_f, bias=False)
        sk_kurt = kurtosis(K_f, fisher=True, bias=False)

        stats = {
            "mean": mean_,
            "std": std_,
            "rms": rms,
            "kurtosis": kurt,
            "skewness": skw,
            "peak_to_peak": p2p,
            "crest_factor": crest,
            "shape_factor": shape_factor,
            "impulse_factor": impulse_factor,
            "margin_factor": margin_factor,
            "energy": energy,
            "spectral_kurtosis_mean": sk_mean,
            "spectral_kurtosis_std": sk_std,
            "spectral_kurtosis_skewness": sk_skew,
            "spectral_kurtosis_kurtosis": sk_kurt,
        }
        return {f"{value_col}_{k}": v for k, v in stats.items()}

    def process_file(self, file, cols):
        logging.info(f"about to read file {file}")
        df = pl.read_parquet(file)
        trial = str(file).split("/")[-1].split(".")[0]
        results = []
        runs = list(df.group_by("run", maintain_order=True))
        for run_id, run_df in tqdm(runs, desc="Calculating Summary Statistics"):
            stats = {}
            for col in cols:
                if col not in df.columns:
                    continue
                rate = 1000 if col == "Power" else 51_20
                stats |= self.compute_row_stats(run_df, col, SAMPLE_RATE=rate)

            stats["trial"] = trial
            stats["run"] = run_id[0] if isinstance(run_id, tuple) else run_id
            stats["fault_mode"] = run_df["fault_mode"][0]
            stats["routine"] = run_df["routine"][0]
            results.append(stats)
        return results

    # -------------------------------------------------------------------------------

    def bronze_layer(self, signal_cols, min_samples=25):
        # expects to be given 'path': the path to the dir to save bronze layer data
        logging.info("BRONZE LAYER: beginning checks...")

        files = list(Path(self.data_path).glob("*.parquet"))

        for f in tqdm(files, desc="checking for missing data"):
            missing = self.bronze_check_missing_data(str(f))
            if missing > 0:
                logging.warning(f"{f.name}: {missing} missing values found")

            df = pl.read_parquet(f)
            bad_runs = self.bronze_check_bad_runs(
                df, signal_cols, min_samples=min_samples
            )

            if bad_runs:
                logging.warning(
                    f"{f.name}: dropping {len(bad_runs)} bad runs: {sorted(bad_runs)}"
                )
                df = df.filter(~pl.col("run").is_in(list(bad_runs)))

            df.write_parquet(Path(self.bronze_data_path) / f.name)
        logging.info(f"BRONZE LAYER: Done! Saved Files to {self.bronze_data_path}")

    def silver_layer(
        self,
        cols: list,
        sampling_rate=-1,
        run_override=False,
    ):
        if not (Path(self.bronze_data_path).exists()):
            logging.error(
                f"ERROR: no data files found in supplied bronze path {self.bronze_data_path}!"
            )
        if (Path(self.silver_data_path).exists()) and (not run_override):
            logging.info("Silver data already generated, skipping...")
            return None
        logging.info("SILVER LAYER: beginning checks...")
        files = list(Path(self.bronze_data_path).glob("*.parquet"))
        # ---- Calculate Summary Statistics

        results = []
        for file in files:
            results.extend(self.process_file(file, cols))

        silver_df = pl.DataFrame(results)

        silver_df.write_parquet(self.silver_data_path)
        logging.info(f"SILVER LAYER: Done! Saved File to {self.silver_data_path}")

    def gold_layer(self, signal_cols):
        logging.info("GOLD LAYER: starting...")
        if not Path(self.silver_data_path).exists():
            logging.info("Silver layer data not found, running Silver layer...")
            self.silver_layer(signal_cols)

        df = pl.read_parquet(self.silver_data_path)
        df = self.gold_remove_outliers(df)
        exclude_cols = ["trial", "run", "fault_mode", "routine"]
        feature_cols = [c for c in df.columns if c not in exclude_cols]

        # --- Global PCA (whole dataset, one shared coordinate system) ---
        logging.info("GOLD LAYER: Running PCA globally...")
        X = df.select(feature_cols).to_numpy()
        X_scaled = StandardScaler().fit_transform(X)
        global_pca = PCA(n_components=3)
        global_components = global_pca.fit_transform(X_scaled)
        logging.info(f"GLOBAL EXPLAINED VARIANCE: {global_pca.explained_variance_ratio_}")

        global_pc_cols = [
            pl.Series(f"dataset_PCA{i+1}", global_components[:, i])
            for i in range(global_components.shape[1])
        ]
        df = df.with_columns(global_pc_cols)

        # --- Per-routine PCA (own coordinate system per routine) ---
        routine_frames = []
        for routine in tqdm(
            df["routine"].unique().to_list(), desc="Processing Features for PCA"
        ):
            logging.info(f"GOLD LAYER: Running PCA for {routine}...")
            sub_df = df.filter(pl.col("routine") == routine)
            X_r = sub_df.select(feature_cols).to_numpy()
            X_r_scaled = StandardScaler().fit_transform(X_r)
            pca = PCA(n_components=3)
            components = pca.fit_transform(X_r_scaled)
            logging.info(f"  {routine} explained variance: {pca.explained_variance_ratio_}")

            pc_cols = [
                pl.Series(f"PC{i+1}", components[:, i])
                for i in range(components.shape[1])
            ]
            keep_cols = ["trial", "run", "fault_mode", "routine"] + [f"dataset_PCA{i+1}" for i in range(global_components.shape[1])]
            sub_df = sub_df.select(keep_cols).with_columns(pc_cols)
            routine_frames.append(sub_df)

        gold_df = pl.concat(routine_frames)
        gold_df = self.gold_remove_outliers(gold_df)
        gold_df.write_parquet(self.gold_data_path)
        logging.info(f"GOLD LAYER: Done! Saved File to {self.gold_data_path}")

# ---- command line running
# example usage:
# > python pipeline.py
# > python pipeline.py --path code/other_output --run-override
# > python pipeline.py --cols SpindleAccX Power --skip-bronze
def main():
    parser = argparse.ArgumentParser(description="Run Pipeline")
    parser.add_argument(
        "--data_path", default="code/parquet_output", help="Pipeline output path"
    )
    parser.add_argument(
        "--cols",
        nargs="+",
        default=[
            "SpindleAccX",
            "SpindleAccY",
            "SpindleAccZ",
            "PlateLFAccX",
            "PlateLFAccY",
            "PlateLFAccZ",
            "PlateHFAccZ",
            "Power",
        ],
        help="Columns to process in silver layer",
    )
    parser.add_argument(
        "--bronze-data-path",
        default="code/bronze_data",
        help="Where the bronze layer saves its output data files to",
    )
    parser.add_argument(
        "--silver-data-path",
        default="code/silver_data/silver_layer.parquet",
        help="Where the silver layer saves its output data file to",
    )
    parser.add_argument(
        "--gold-data-path",
        default="code/gold_data/gold_layer.parquet",
        help="Where the silver layer saves its output data file to",
    )

    parser.add_argument(
        "--silver-run-override",
        action="store_true",
        help="Force re-run even if output exists",
    )
    parser.add_argument(
        "--skip-bronze-checks",
        action="store_true",
        help="Skip the bronze layer step",
    )
    parser.add_argument("--verbose", action="store_true", help="show logs in terminal")

    args = parser.parse_args()

    handlers = [logging.FileHandler("pipeline.log")]
    if args.verbose:
        handlers.append(logging.StreamHandler())

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=handlers,
        force=True,
    )

    pipeline = Pipeline(
        args.data_path,
        args.bronze_data_path,
        args.silver_data_path,
        args.gold_data_path,
    )

    if not args.skip_bronze_checks:
        pipeline.bronze_layer(signal_cols=args.cols)

    pipeline.silver_layer(
        cols=args.cols,
        run_override=args.silver_run_override,
    )

    pipeline.gold_layer(signal_cols=args.cols)


if __name__ == "__main__":
    main()
